const pages = await (await fetch('http://localhost:9223/json')).json();
const page = pages.find((item) => item.url === 'http://localhost:3453/');
if (!page) throw new Error('QA page not found');
const ws = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject; });
let id = 0;
const pending = new Map();
ws.onmessage = ({ data }) => { const message = JSON.parse(data); if (message.id && pending.has(message.id)) { pending.get(message.id)(message); pending.delete(message.id); } };
const send = (method, params = {}) => new Promise((resolve) => { const callId = ++id; pending.set(callId, resolve); ws.send(JSON.stringify({ id: callId, method, params })); });
const evaluate = async (expression) => (await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true })).result?.result?.value;
const wait = (ms = 250) => new Promise((resolve) => setTimeout(resolve, ms));
const assert = (condition, label) => { if (!condition) throw new Error(label); console.log(`PASS ${label}`); };
const click = async (label) => { assert(await evaluate(`(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.innerText.trim().includes(${JSON.stringify(label)}));if(!b)return false;b.click();return true})()`), `control exists: ${label}`); await wait(); };

await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
await evaluate(`localStorage.clear(); location.reload()`); await wait(900);
const desktop = await evaluate(`(()=>{const cards=[...document.querySelectorAll('.playbook-card')], covers=[...document.querySelectorAll('.cover')];return {overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,columns:new Set(cards.slice(0,4).map(x=>Math.round(x.getBoundingClientRect().top))).size,cards:cards.map(x=>({w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height,right:x.getBoundingClientRect().right})),ratios:covers.map(x=>x.getBoundingClientRect().width/x.getBoundingClientRect().height),unnamed:[...document.querySelectorAll('button,input,select,textarea')].filter(x=>!(x.getAttribute('aria-label')||x.getAttribute('aria-labelledby')||x.innerText?.trim()||x.labels?.length||x.placeholder)).length}})()`);
assert(!desktop.overflow, 'desktop has no horizontal overflow');
assert(desktop.columns === 1, 'desktop playbooks align in one four-card row');
assert(desktop.cards.every((card) => card.w >= 220 && card.right <= 1440), 'desktop cards are readable and inside viewport');
assert(desktop.ratios.every((ratio) => Math.abs(ratio - 16 / 9) < .04), 'cover photos keep a 16:9 ratio');
assert(desktop.unnamed === 0, 'interactive controls have accessible names');
await click('Settings');
assert(await evaluate(`document.body.innerText.includes('Add location') && document.body.innerText.includes('User access')`), 'location management and sharing guidance live in Settings');
await click('Add location');
await evaluate(`(()=>{const e=document.querySelector('.location-name-field input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,'QA Uptown');e.dispatchEvent(new Event('input',{bubbles:true}));})()`); await wait();
await click('Create location');
assert(await evaluate(`document.querySelector('.shop select').value.includes('qa-uptown') && document.body.innerText.includes('QA Uptown')`), 'location creation activates the named location');
assert(await evaluate(`document.body.innerText.includes('Boba Bloom Downtown')`), 'location switcher exposes the second location');
await evaluate(`(()=>{const s=document.querySelector('.shop select');s.value='boba-bloom-downtown';s.dispatchEvent(new Event('change',{bubbles:true}));})()`); await wait();
const arts = await evaluate(`[...document.querySelectorAll('.playbook-card')].map(x=>({title:x.querySelector('h3')?.innerText,art:x.querySelector('.cover')?.className}))`);
assert(arts.some((x) => x.title.includes('Jasmine') && x.art.includes('jasmine')), 'Jasmine playbook uses the Jasmine cover');
assert(arts.some((x) => x.title.includes('Cleaning') && x.art.includes('cleaning')), 'cleaning playbook uses the cleaning cover');

await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true }); await wait(350);
assert(await evaluate(`document.documentElement.scrollWidth<=document.documentElement.clientWidth`), 'mobile has no horizontal overflow');
assert(await evaluate(`getComputedStyle(document.querySelector('.cardgrid')).gridTemplateColumns.split(' ').length===1`), 'mobile cards use one readable column');
await click('Create playbook');
assert(await evaluate(`(()=>{const m=document.querySelector('.create-modal');return m.scrollHeight<=m.clientHeight||getComputedStyle(m).overflowY==='auto'||document.querySelector('.overlay').scrollHeight>=m.scrollHeight})()`), 'create modal remains scrollable on mobile');
ws.close();
